In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\ravib\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ravib\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\ravib\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp314-cp314-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   -------------------- ------------------- 5.0/9.8 MB 31.6 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 29.3 MB/s  0:00:00
Downloading tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.6 tzdata-2026.5

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\ravib\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

3.0.3

In [4]:
l = [100,200,300,400,500]
series = pd.Series(l)
series
#Note: It is automatically assigned an index 0 to n-1, where n is the number of elements in the series.

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [5]:
# If you want to assign your own index, you can do so by passing the index parameter while creating the series.
l = [100,200,300,400,500]
series = pd.Series(l, index=['a','b','c','d','e'])
series

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [12]:
# You can access the elements of the series using the index labels. For example, to access the element with index 'a', you can use:
series.loc['a']

np.int64(100)

In [13]:
# You can also access the elements using the integer index position. For example, to access the first element of the series, you can use:
series.iloc[0]

np.int64(100)

In [14]:
# Create a pandas Series from a dictionary
walk = {"Day1": 1000, "Day2": 2000, "Day3": 3000}
walk_series = pd.Series(walk)
walk_series

Day1    1000
Day2    2000
Day3    3000
dtype: int64

In [15]:
walk_series.loc['Day1']+=200
walk_series

Day1    1200
Day2    2000
Day3    3000
dtype: int64

In [18]:
# Create a DataFrame with custom index
employee = {"Name": ["John", "Ravi", "Bhushan"],
            "age": [25, 30, 35],
            "department": ["HR", "IT", "Finance"]}
a=pd.DataFrame(employee)
a

      Name  age department
0     John   25         HR
1     Ravi   30         IT
2  Bhushan   35    Finance

In [19]:
# Create a DataFrame with custom index
employee = {"Name": ["John", "Ravi", "Bhushan"],
            "age": [25, 30, 35],
            "department": ["HR", "IT", "Finance"]}
a=pd.DataFrame(employee,["emp1","emp2","emp3"])
a

         Name  age department
emp1     John   25         HR
emp2     Ravi   30         IT
emp3  Bhushan   35    Finance

In [20]:
# Select the row for employee with index 'emp1'
a.loc['emp1']

Name          John
age             25
department      HR
Name: emp1, dtype: object

In [21]:
# Add a new column for Salary
a["Salary"] = [50000, 60000, 70000]
a

         Name  age department  Salary
emp1     John   25         HR   50000
emp2     Ravi   30         IT   60000
emp3  Bhushan   35    Finance   70000

In [22]:
# Add a new row
new_row=pd.DataFrame({"Name":["Ramesh"],"age":[28],"department":["IT"],"Salary":[65000]},index=["emp4"])
new_row

        Name  age department  Salary
emp4  Ramesh   28         IT   65000

In [43]:
# Concatenate the new row to the existing DataFrame
a = pd.concat([a, new_row])
a

         Name  age department  Salary
emp1     John   25         HR   50000
emp2     Ravi   30         IT   60000
emp3  Bhushan   35    Finance   70000
emp4   Ramesh   28         IT   65000
emp4   Ramesh   28         IT   65000

In [42]:
# Read data from a CSV file
data = pd.read_csv("Data.csv")
data

      No        Name  Height  Weight     Type1     Type2  Legendary
0      1   Bulbasaur     4.7    11.4  Electric       Ice      False
1      2     Ivysaur     5.9   126.4  Fighting     Ghost      False
2      3    Venusaur     1.0   125.3   Psychic       NaN      False
3      4  Charmander     6.2   264.0     Grass  Fighting      False
4      5  Charmeleon     6.4   234.1      Rock      Rock      False
..   ...         ...     ...     ...       ...       ...        ...
145  146     Moltres     6.2   134.1     Fairy      Fire       True
146  147     Dratini     4.7   255.5    Normal   Psychic      False
147  148  Pokemon148     6.7   193.1     Water     Grass      False
148  149  Pokemon149     4.8    79.9    Ground    Flying      False
149  150  Pokemon150     2.2    91.9  Electric    Flying       True

[150 rows x 7 columns]

In [44]:
# to display the entire DataFrame without truncation, you can use the `to_string()` method. This will print the entire DataFrame as a string representation, allowing you to see all rows and columns without any truncation.
data.to_string()

'      No        Name  Height  Weight     Type1     Type2  Legendary\n0      1   Bulbasaur     4.7    11.4  Electric       Ice      False\n1      2     Ivysaur     5.9   126.4  Fighting     Ghost      False\n2      3    Venusaur     1.0   125.3   Psychic       NaN      False\n3      4  Charmander     6.2   264.0     Grass  Fighting      False\n4      5  Charmeleon     6.4   234.1      Rock      Rock      False\n5      6   Charizard     2.1     6.8    Flying  Fighting      False\n6      7    Squirtle     6.7   120.0   Psychic     Water      False\n7      8   Wartortle     2.0   297.2    Normal  Fighting      False\n8      9   Blastoise     4.9   254.1     Fairy    Dragon      False\n9     10    Caterpie     3.7   216.6     Ghost     Ghost      False\n10    11     Metapod     6.4   164.4      Rock       Ice      False\n11    12  Butterfree     2.4   165.1     Grass  Fighting      False\n12    13      Weedle     2.4    19.4  Fighting    Dragon      False\n13    14      Kakuna     6.4   279.2  Fighting     Water      False\n14    15    Beedrill     3.4   195.9     Water     Fairy      False\n15    16      Pidgey     4.8   239.6    Normal      Fire      False\n16    17   Pidgeotto     5.8   152.2    Poison       Bug      False\n17    18     Pidgeot     0.5   297.9  Electric    Flying      False\n18    19     Rattata     2.0   137.4     Ghost    Poison      False\n19    20    Raticate     2.3   216.7    Flying    Dragon      False\n20    21     Spearow     0.6    48.2  Fighting    Poison      False\n21    22      Fearow     1.2   219.6    Dragon       NaN      False\n22    23       Ekans     3.3   124.4       Ice    Poison      False\n23    24       Arbok     2.8     4.6    Dragon      Fire      False\n24    25     Pikachu     4.7    70.4      Fire       NaN      False\n25    26      Raichu     6.7   287.9      Fire     Ghost      False\n26    27   Sandshrew     3.9   237.3       Ice     Water      False\n27    28   Sandslash     5.9    65.8       Bug    Ground      False\n28    29    NidoranF     3.6     8.5     Ghost       NaN      False\n29    30    Nidorina     6.1   198.9  Electric       NaN      False\n30    31   Nidoqueen     5.6    17.3      Fire  Electric      False\n31    32    NidoranM     3.6    67.2    Flying       Ice      False\n32    33    Nidorino     1.1   135.9       Bug     Grass      False\n33    34    Nidoking     2.0   238.9    Flying     Water      False\n34    35    Clefairy     3.9   211.7  Electric       NaN      False\n35    36    Clefable     3.5   153.5  Electric  Electric      False\n36    37      Vulpix     2.7   272.7   Psychic  Fighting      False\n37    38   Ninetales     5.8   200.2     Ghost    Ground      False\n38    39  Jigglypuff     4.3   207.7    Dragon       NaN      False\n39    40  Wigglytuff     4.2    61.2   Psychic       Ice      False\n40    41       Zubat     2.7   199.8  Fighting    Ground      False\n41    42      Golbat     6.2    27.0    Normal      Fire      False\n42    43      Oddish     3.8    97.8    Normal      Rock      False\n43    44       Gloom     7.0   191.1    Dragon       Ice      False\n44    45   Vileplume     5.6   261.7    Ground     Fairy      False\n45    46       Paras     3.4   272.4      Fire    Normal      False\n46    47    Parasect     1.8   240.9     Water  Electric      False\n47    48     Venonat     0.6   193.1    Ground     Ghost      False\n48    49    Venomoth     0.5    90.3     Ghost     Fairy      False\n49    50     Diglett     5.8    60.2    Poison    Dragon      False\n50    51     Dugtrio     3.3   224.9     Water  Fighting      False\n51    52      Meowth     0.5    95.2      Rock       NaN      False\n52    53     Persian     4.7   228.7  Electric     Fairy      False\n53    54     Psyduck     4.9   224.1     Ghost     Ghost      False\n54    55     Golduck     0.4    76.7    Ground       NaN      False\n55    56      Mankey     5.2   277.4    Normal    Poison      False\n56    57    Primeape     4.0   257.9     Ghost    Normal      False\n57    58   Growlithe     3.5    70.3    Flying     Grass      False\n58    59    Arcanine     5.0    30.7  Fighting    Normal      False\n59    60     Poliwag     3.0   202.1     Grass    Poison      False\n60    61   Poliwhirl     1.1   137.8     Ghost       Bug      False\n61    62   Poliwrath     1.4    65.8    Normal     Water      False\n62    63        Abra     5.7    46.0       Ice     Fairy      False\n63    64     Kadabra     6.1   282.8  Electric      Rock      False\n64    65    Alakazam     6.7   262.0    Dragon  Electric      False\n65    66      Machop     4.3   144.3    Flying       NaN      False\n66    67     Machoke     0.8   186.8    Poison       Bug      False\n67    68     Machamp     6.0    71.7  Electric    Poison      False\n68    69  Bellsprout     5.3   281.5   Psychic    Poison      False\n69    70  Weepinbell     1.1   279.0    Ground      Rock      False\n70    71  Victreebel     5.7   117.9  Fighting       Bug      False\n71    72   Tentacool     5.5   298.6    Dragon      Fire      False\n72    73  Tentacruel     1.8   271.5    Dragon  Electric      False\n73    74     Geodude     3.8   243.8     Fairy  Electric      False\n74    75    Graveler     4.0   104.9    Ground    Normal      False\n75    76       Golem     0.4   291.0     Ghost    Poison      False\n76    77      Ponyta     5.7   100.5    Dragon    Ground      False\n77    78    Rapidash     0.9    54.8     Fairy    Dragon      False\n78    79    Slowpoke     4.1   276.3    Normal     Ghost      False\n79    80     Slowbro     6.9   152.4     Ghost     Fairy      False\n80    81   Magnemite     2.3    95.4    Dragon  Electric      False\n81    82    Magneton     3.9    30.8    Ground    Dragon      False\n82    83   Farfetchd     6.4   241.7    Ground     Ghost      False\n83    84       Doduo     5.8   194.3   Psychic   Psychic      False\n84    85      Dodrio     6.6    84.6  Fighting     Water      False\n85    86        Seel     3.9    50.5     Water       NaN      False\n86    87     Dewgong     0.7   134.3    Dragon   Psychic      False\n87    88      Grimer     5.0   122.9     Grass       NaN      False\n88    89         Muk     2.4    64.0     Grass     Fairy      False\n89    90    Shellder     5.8   255.0     Fairy       Ice      False\n90    91    Cloyster     1.0    29.6     Ghost  Electric      False\n91    92      Gastly     4.3    84.3      Fire     Fairy      False\n92    93     Haunter     2.7   196.4  Electric     Fairy      False\n93    94      Gengar     2.9    44.5  Fighting    Flying      False\n94    95        Onix     5.1   256.0    Dragon      Fire      False\n95    96     Drowzee     0.4    52.9   Psychic      Fire      False\n96    97       Hypno     6.1   257.4      Rock     Grass      False\n97    98      Krabby     5.8   174.6     Grass      Rock      False\n98    99     Kingler     3.9    35.9       Bug      Fire      False\n99   100     Voltorb     4.5   290.6      Fire     Ghost      False\n100  101   Electrode     1.9    11.4   Psychic       Ice      False\n101  102   Exeggcute     1.3    82.0       Ice    Flying      False\n102  103   Exeggutor     5.9   125.7    Flying   Psychic      False\n103  104      Cubone     1.7   293.0  Electric  Electric      False\n104  105     Marowak     2.9    51.2     Fairy    Dragon      False\n105  106   Hitmonlee     1.1   148.1    Dragon       Ice      False\n106  107  Hitmonchan     1.8   263.1    Flying    Flying      False\n107  108   Lickitung     0.7   222.6       Ice      Fire      False\n108  109     Koffing     4.1   246.2  Electric       NaN      False\n109  110     Weezing     4.4   114.4   Psychic     Grass      False\n110  111     Rhyhorn     5.7   102.7    Dragon  Fighting      False\n111  112      Rhydon     2.2     6.7    Poison       NaN      False\n112  113     Chansey     0.3   129.8    Poison       Bug      False\n113  114     Tangela     6.6   163.9  Electric      Fire      False\n114  115  Kangaskhan     5.0    62.9       Ice       Ice      False\n115  116      Horsea     4.1    93.8    Flying       Ice      False\n116  117      Seadra     3.9   225.4   Psychic    Poison      False\n117  118     Goldeen     3.9   177.2  Electric  Electric      False\n118  119     Seaking     6.0   203.4  Electric    Flying      False\n119  120      Staryu     3.7    66.3    Dragon       NaN      False\n120  121     Starmie     3.8   220.2    Ground    Ground      False\n121  122      MrMime     3.9   211.5     Water     Water      False\n122  123     Scyther     5.7    46.6     Grass      Fire      False\n123  124        Jynx     6.8   129.4     Fairy    Normal      False\n124  125  Electabuzz     4.8   245.2       Bug       NaN      False\n125  126      Magmar     1.6   107.5    Dragon    Flying      False\n126  127      Pinsir     4.0   169.7      Rock      Rock      False\n127  128      Tauros     0.6    97.3     Ghost  Electric      False\n128  129    Magikarp     4.4    71.1    Poison     Ghost      False\n129  130    Gyarados     2.9   236.5     Fairy   Psychic      False\n130  131      Lapras     3.6   173.6       Ice     Ghost      False\n131  132       Ditto     0.7   160.8     Fairy      Rock      False\n132  133       Eevee     4.8   242.7      Fire    Poison      False\n133  134    Vaporeon     4.3   191.7       Ice       NaN      False\n134  135     Jolteon     1.4   216.0   Psychic   Psychic      False\n135  136     Flareon     4.8   268.7      Rock    Flying      False\n136  137     Porygon     4.6    53.3       Bug      Rock      False\n137  138     Omanyte     5.3   300.0       Bug       NaN      False\n138  139     Omastar     3.5   209.4      Rock   Psychic      False\n139  140      Kabuto     4.0   151.6    Ground       Ice      False\n140  141    Kabutops     2.0   194.7       Bug      Rock      False\n141  142  Aerodactyl     4.6    44.4     Water       Bug      False\n142  143     Snorlax     1.7    54.2     Ghost       NaN      False\n143  144    Articuno     3.8   103.2     Water       NaN       True\n144  145      Zapdos     3.7    35.1  Electric       Ice       True\n145  146     Moltres     6.2   134.1     Fairy      Fire       True\n146  147     Dratini     4.7   255.5    Normal   Psychic      False\n147  148  Pokemon148     6.7   193.1     Water     Grass      False\n148  149  Pokemon149     4.8    79.9    Ground    Flying      False\n149  150  Pokemon150     2.2    91.9  Electric    Flying       True'

In [45]:
data.head()  # Display the first 10 rows of the DataFrame

   No        Name  Height  Weight     Type1     Type2  Legendary
0   1   Bulbasaur     4.7    11.4  Electric       Ice      False
1   2     Ivysaur     5.9   126.4  Fighting     Ghost      False
2   3    Venusaur     1.0   125.3   Psychic       NaN      False
3   4  Charmander     6.2   264.0     Grass  Fighting      False
4   5  Charmeleon     6.4   234.1      Rock      Rock      False

In [46]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   No         150 non-null    int64
 1   Name       150 non-null    str
 2   Height     150 non-null    float64
 3   Weight     150 non-null    float64
 4   Type1      150 non-null    str
 5   Type2      130 non-null    str
 6   Legendary  150 non-null    bool
dtypes: bool(1), float64(2), int64(1), str(3)
memory usage: 9.9 KB

In [48]:
data.describe()  # Get summary statistics of the DataFrame

               No      Height      Weight
count  150.000000  150.000000  150.000000
mean    75.500000    3.782000  156.811333
std     43.445368    1.895635   86.901000
min      1.000000    0.300000    4.600000
25%     38.250000    2.200000   77.500000
50%     75.500000    3.900000  157.150000
75%    112.750000    5.450000  235.900000
max    150.000000    7.000000  300.000000

In [49]:
data["No"]

0        1
1        2
2        3
3        4
4        5
      ...
145    146
146    147
147    148
148    149
149    150
Name: No, Length: 150, dtype: int64

In [50]:
data[[ "No" ,"Height","Weight"]]

      No  Height  Weight
0      1     4.7    11.4
1      2     5.9   126.4
2      3     1.0   125.3
3      4     6.2   264.0
4      5     6.4   234.1
..   ...     ...     ...
145  146     6.2   134.1
146  147     4.7   255.5
147  148     6.7   193.1
148  149     4.8    79.9
149  150     2.2    91.9

[150 rows x 3 columns]

In [52]:
height = data[data["Height"] > 5]
height

      No        Name  Height  Weight     Type1     Type2  Legendary
1      2     Ivysaur     5.9   126.4  Fighting     Ghost      False
3      4  Charmander     6.2   264.0     Grass  Fighting      False
4      5  Charmeleon     6.4   234.1      Rock      Rock      False
6      7    Squirtle     6.7   120.0   Psychic     Water      False
10    11     Metapod     6.4   164.4      Rock       Ice      False
13    14      Kakuna     6.4   279.2  Fighting     Water      False
16    17   Pidgeotto     5.8   152.2    Poison       Bug      False
25    26      Raichu     6.7   287.9      Fire     Ghost      False
27    28   Sandslash     5.9    65.8       Bug    Ground      False
29    30    Nidorina     6.1   198.9  Electric       NaN      False
30    31   Nidoqueen     5.6    17.3      Fire  Electric      False
37    38   Ninetales     5.8   200.2     Ghost    Ground      False
41    42      Golbat     6.2    27.0    Normal      Fire      False
43    44       Gloom     7.0   191.1    Dragon       Ice      False
44    45   Vileplume     5.6   261.7    Ground     Fairy      False
49    50     Diglett     5.8    60.2    Poison    Dragon      False
55    56      Mankey     5.2   277.4    Normal    Poison      False
62    63        Abra     5.7    46.0       Ice     Fairy      False
63    64     Kadabra     6.1   282.8  Electric      Rock      False
64    65    Alakazam     6.7   262.0    Dragon  Electric      False
67    68     Machamp     6.0    71.7  Electric    Poison      False
68    69  Bellsprout     5.3   281.5   Psychic    Poison      False
70    71  Victreebel     5.7   117.9  Fighting       Bug      False
71    72   Tentacool     5.5   298.6    Dragon      Fire      False
76    77      Ponyta     5.7   100.5    Dragon    Ground      False
79    80     Slowbro     6.9   152.4     Ghost     Fairy      False
82    83   Farfetchd     6.4   241.7    Ground     Ghost      False
83    84       Doduo     5.8   194.3   Psychic   Psychic      False
84    85      Dodrio     6.6    84.6  Fighting     Water      False
89    90    Shellder     5.8   255.0     Fairy       Ice      False
94    95        Onix     5.1   256.0    Dragon      Fire      False
96    97       Hypno     6.1   257.4      Rock     Grass      False
97    98      Krabby     5.8   174.6     Grass      Rock      False
102  103   Exeggutor     5.9   125.7    Flying   Psychic      False
110  111     Rhyhorn     5.7   102.7    Dragon  Fighting      False
113  114     Tangela     6.6   163.9  Electric      Fire      False
118  119     Seaking     6.0   203.4  Electric    Flying      False
122  123     Scyther     5.7    46.6     Grass      Fire      False
123  124        Jynx     6.8   129.4     Fairy    Normal      False
137  138     Omanyte     5.3   300.0       Bug       NaN      False
145  146     Moltres     6.2   134.1     Fairy      Fire       True
147  148  Pokemon148     6.7   193.1     Water     Grass      False

In [53]:
height=data[(data["Height"] > 5) & (data["Weight"] > 50)]
height

      No        Name  Height  Weight     Type1     Type2  Legendary
1      2     Ivysaur     5.9   126.4  Fighting     Ghost      False
3      4  Charmander     6.2   264.0     Grass  Fighting      False
4      5  Charmeleon     6.4   234.1      Rock      Rock      False
6      7    Squirtle     6.7   120.0   Psychic     Water      False
10    11     Metapod     6.4   164.4      Rock       Ice      False
13    14      Kakuna     6.4   279.2  Fighting     Water      False
16    17   Pidgeotto     5.8   152.2    Poison       Bug      False
25    26      Raichu     6.7   287.9      Fire     Ghost      False
27    28   Sandslash     5.9    65.8       Bug    Ground      False
29    30    Nidorina     6.1   198.9  Electric       NaN      False
37    38   Ninetales     5.8   200.2     Ghost    Ground      False
43    44       Gloom     7.0   191.1    Dragon       Ice      False
44    45   Vileplume     5.6   261.7    Ground     Fairy      False
49    50     Diglett     5.8    60.2    Poison    Dragon      False
55    56      Mankey     5.2   277.4    Normal    Poison      False
63    64     Kadabra     6.1   282.8  Electric      Rock      False
64    65    Alakazam     6.7   262.0    Dragon  Electric      False
67    68     Machamp     6.0    71.7  Electric    Poison      False
68    69  Bellsprout     5.3   281.5   Psychic    Poison      False
70    71  Victreebel     5.7   117.9  Fighting       Bug      False
71    72   Tentacool     5.5   298.6    Dragon      Fire      False
76    77      Ponyta     5.7   100.5    Dragon    Ground      False
79    80     Slowbro     6.9   152.4     Ghost     Fairy      False
82    83   Farfetchd     6.4   241.7    Ground     Ghost      False
83    84       Doduo     5.8   194.3   Psychic   Psychic      False
84    85      Dodrio     6.6    84.6  Fighting     Water      False
89    90    Shellder     5.8   255.0     Fairy       Ice      False
94    95        Onix     5.1   256.0    Dragon      Fire      False
96    97       Hypno     6.1   257.4      Rock     Grass      False
97    98      Krabby     5.8   174.6     Grass      Rock      False
102  103   Exeggutor     5.9   125.7    Flying   Psychic      False
110  111     Rhyhorn     5.7   102.7    Dragon  Fighting      False
113  114     Tangela     6.6   163.9  Electric      Fire      False
118  119     Seaking     6.0   203.4  Electric    Flying      False
123  124        Jynx     6.8   129.4     Fairy    Normal      False
137  138     Omanyte     5.3   300.0       Bug       NaN      False
145  146     Moltres     6.2   134.1     Fairy      Fire       True
147  148  Pokemon148     6.7   193.1     Water     Grass      False

In [54]:
height=data[(data["Height"] > 5) & (data["Weight"] > 50) &(data["Type1"]=="Grass")]
height

    No        Name  Height  Weight  Type1     Type2  Legendary
3    4  Charmander     6.2   264.0  Grass  Fighting      False
97  98      Krabby     5.8   174.6  Grass      Rock      False

In [55]:
# To remove the column "Legendary" from the DataFrame, you can use the `drop()` method. Here's how you can do it:
d1 = data.drop(columns=["Legendary"])
d1

      No        Name  Height  Weight     Type1     Type2
0      1   Bulbasaur     4.7    11.4  Electric       Ice
1      2     Ivysaur     5.9   126.4  Fighting     Ghost
2      3    Venusaur     1.0   125.3   Psychic       NaN
3      4  Charmander     6.2   264.0     Grass  Fighting
4      5  Charmeleon     6.4   234.1      Rock      Rock
..   ...         ...     ...     ...       ...       ...
145  146     Moltres     6.2   134.1     Fairy      Fire
146  147     Dratini     4.7   255.5    Normal   Psychic
147  148  Pokemon148     6.7   193.1     Water     Grass
148  149  Pokemon149     4.8    79.9    Ground    Flying
149  150  Pokemon150     2.2    91.9  Electric    Flying

[150 rows x 6 columns]